export enum ActionTypes {
  CUSTOMER_AUTHENTICATED = "app/containers/Authentication/CUSTOMER_AUTHENTICATED",
  CUSTOMER_UNAUTHENTICATED = "app/containers/Authentication/CUSTOMER_UNAUTHENTICATED",
  SPECIALIST_AUTHENTICATED = "app/containers/Authentication/SPECIALIST_AUTHENTICATED",
  SPECIALIST_UNAUTHENTICATED = "app/containers/Authentication/SPECIALIST_UNAUTHENTICATED",
  ADMIN_AUTHENTICATED = "app/containers/Authentication/ADMIN_AUTHENTICATED",
  ADMIN_UNAUTHENTICATED = "app/containers/Authentication/ADMIN_UNAUTHENTICATED",
  SET_AUTHENTICATED_USER = "app/containers/Authentication/SET_AUTHENTICATED_USER",
}
